on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04-x64
    steps:
      - name: Install Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git
          git clone https://github.com/rbenv/ruby-build.git ~/.ruby-build
          sudo ~/.ruby-build/install.sh
          ruby-build 3.1.4 $RUNNER_TOOL_CACHE/ruby-3.1.4
          echo 'export PATH="$RUNNER_TOOL_CACHE/ruby-3.1.4/bin:$PATH"' >> $GITHUB_ENV
      - name: Verify Ruby Installation
        run: ruby --version
