on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04-x64
    steps:
      - name: Set up Ruby
        run: |
          git clone https://github.com/rbenv/ruby-build.git ~/.ruby-build
          ~/.ruby-build/install.sh
          rbenv install 3.1.0
          rbenv global 3.1.0
          ruby -v
      - name: Install Bundler
        run: gem install bundler
      - name: Install dependencies
        run: bundle install